[tool.poetry]
name = "poetry_docker"
version = "0.1.0"
description = ""
authors = ["yolo-kiyoshi"]

[tool.poetry.dependencies]
python = "^3.7"
streamlit = "^0.61.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
